dist: xenial
language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0

matrix:
  exclude:
    - env: DJANGO=3.0
      python: 3.5


install:
  - pip install tox

script:
  - tox -e "d${DJANGO//.}-py${TRAVIS_PYTHON_VERSION//.}" -- py.test src tests -W ignore  --capture=no

before_success:
  - coverage erase

after_success:
  - coverage combine
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/825f521b72e421171f8e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
